/**
 * Supplier Mappings
 * Generated from suppliers-import.csv
 * Date: 2025-11-13T14:58:19.196Z
 * Total suppliers: 1398
 */

export const SUPPLIER_MAPPINGS: Record<string, string> = {
  'AANB': 'Reijnders Graveer & Lasertechniek BV',
  'BNEACCP1200': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCAPD': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCD': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCSP': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCVESA200400': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCVESA75100': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCW': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCWE': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCWE5015': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEACCLP': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEASBB': 'Reijnders Graveer & Lasertechniek BV',
  'BNEASNEW': 'Reijnders Graveer & Lasertechniek BV',
  'BNEASSDR': 'Loctek Ningbo International Trading Co. Ltd',
  'BNEASSDR2B': 'Loctek Ningbo International Trading Co. Ltd',
  'BNEASSDR2W': 'Loctek Ningbo International Trading Co. Ltd',
  'BNEASSDRW': 'Loctek Ningbo International Trading Co. Ltd',
  'BNEMUVMB': 'aeris GmbH',
  'BNEMUVMBH': 'aeris GmbH',
  'BNEMUVISB': 'aeris GmbH',
  'BNESWSG': 'aeris GmbH',
  'BNESWSW': 'aeris GmbH',
  'ZZZ_Swopper_101-ST-BK-BK-CP-29': 'aeris GmbH',
  'ZZZ_CHAIR_ASSW': 'aeris GmbH',
  'BNESWCG': 'aeris GmbH',
  'BNESWCW': 'aeris GmbH',
  'ZZZ_SW_102-HB-STBK-BK-CM01': 'aeris GmbH',
  'ZZZ_SW_102-HB-STBK-BK-UR01': 'aeris GmbH',
  'ZZZ_Afstandsbusjes 20x10x13mm': 'Ropro-Europe B.V.',
  'BNEAO2BL': 'ErgoType BV',
  'BNEAO2BR': 'ErgoType BV',
  'ZZZ_PROJECT_AWYS072L_80x45x5': 'TwoWork Partner in Interieurprojecten B.V.',
  'ZZZ_PROJECT_AWYS145L_80x45x5': 'TwoWork Partner in Interieurprojecten B.V.',
  'ZZZ_PROJECT_AWYS072R_80x45x5': 'TwoWork Partner in Interieurprojecten B.V.',
  'ZZZ_PROJECT_AWYS145R_80x45x5': 'TwoWork Partner in Interieurprojecten B.V.',
  'ZZZ_Project_AWYS072_160x45x5': 'TwoWork Partner in Interieurprojecten B.V.',
  'ZZZ_PROJECT_AWYS145_160x45x5': 'TwoWork Partner in Interieurprojecten B.V.',
  'BNELCASEB': 'Ooxy Technology Ltd.',
  'BNELCASEBS': 'Ooxy Technology Ltd.',
  'BNEAMAHB': 'Score BV',
  'BNEAMAHF': 'Score BV',
  'BNEAMAHT': 'Score BV',
  'BNEAMAHTL': 'Score BV',
  'BNEAMALB': 'Score BV',
  'BNEAMALF': 'Score BV',
  'BNEAMALT': 'Score BV',
  'BNEAMALTL': 'Score BV',
  'BNEAMANB': 'Score BV',
  'BNEAMANF': 'Score BV',
  'BNEAMANT': 'Score BV',
  'BNEAMANTL': 'Score BV',
  'BNEALB': 'Adveo Nederland BV',
  'BNEALBW': 'Adveo Nederland BV',
  'BNEAMSB': 'Adveo Nederland BV',
  'BNEAMSBW': 'Adveo Nederland BV',
  'BNEAWMM': 'Five 4 U BV',
  'BNEKENOTSR': 'Ingram Micro BV',
  'BNEAMFAR': 'Prestige International Inc.',
  'BNEAXZ': 'In2Ergo',
  'BNEAXW': 'In2Ergo',
  'BNEBM': 'Ergoption AB / Kenson AB',
  'BNEBMWRS': 'Ergoption AB / Kenson AB',
  'BNEFRB950': 'Score BV',
  'BNEFRB951': 'Score BV',
  'BNEFRB952': 'Score BV',
  'ZZZ_PRO_BNEFRB952ESD': 'Score BV',
  'BNEBFCCB': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFDB': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFDDG': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFDW': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFLCS': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFLCB': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFSB': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFSDG': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBFSW': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNESSBAGRN120': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBAGRN140': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBAGRN160': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBAGRN180': 'Reijnders Graveer & Lasertechniek BV',
  'SSBAHVN100H80': 'Reijnders Graveer & Lasertechniek BV',
  'SSBA100H80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBALGY120': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBALGY130H60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBALGY140': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBALGY160': 'Reijnders Graveer & Lasertechniek BV',
  'SSBALGY160H70': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBALGY180': 'Reijnders Graveer & Lasertechniek BV',
  'SSBEAHVNW100W100H80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBGRN120': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBGRN140': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBGRN160': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBGRN180': 'Reijnders Graveer & Lasertechniek BV',
  'SSBHVN160H43': 'Reijnders Graveer & Lasertechniek BV',
  '"SSBHVN160H44': '5",Reijnders Graveer & Lasertechniek BV',
  'BNESSBLGY120': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBLGY140': 'Reijnders Graveer & Lasertechniek BV',
  'SSBLGY150H35': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBLGY160': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSBLGY180': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSCL12-45': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSCL5-26': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSCAP': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSCLS': 'Reijnders Graveer & Lasertechniek BV',
  'ZZZ_PRO_BNESSLLGY200D80H60': 'Reijnders Graveer & Lasertechniek BV',
  'ZZZ_PRO_BNESSRLGY200D80H60': 'Reijnders Graveer & Lasertechniek BV',
  'ZZZ_PRO_SSSLGYD40': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSABLUD80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSAGRND60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSAGRND80': 'Reijnders Graveer & Lasertechniek BV',
  'SSSAHVNH80D60': 'Reijnders Graveer & Lasertechniek BV',
  'SSSAHVNH80D65': 'Reijnders Graveer & Lasertechniek BV',
  'SSSAHVNH80D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSALGYD60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSALGYD80': 'Reijnders Graveer & Lasertechniek BV',
  'SSSALGYH80D65': 'Reijnders Graveer & Lasertechniek BV',
  'SSSALGYH80D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSGRND60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSGRND80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSLGYD60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSSLGYD80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUABLK120D70': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAGRN140H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAGRN160H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN120D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN120D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN140D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN140D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN160D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN160D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN180D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAGRN180D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAHVN140H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAHVN160H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAHVN100H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAHVN120H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAHVN140H80D90': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUAHVN160D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAHVN180H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUAHVN180H80D90': 'Reijnders Graveer & Lasertechniek BV',
  'SSUALGY140H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUALGY160H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUALGY100H80D75': 'Reijnders Graveer & Lasertechniek BV',
  'SSUALGY110H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY120D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY120D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUALGY120H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY140D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY140D70': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY140D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUALGY140H80D90': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY160D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY160D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY180D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY180D80': 'Reijnders Graveer & Lasertechniek BV',
  'SSUALGY180H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY48D24IN': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUALGY58D23IN': 'Reijnders Graveer & Lasertechniek BV',
  'SSUANGH140H80D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUSALG160D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN120D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN120D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN140D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN140D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN160D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN160D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN180D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSUGRN180D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY120D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY120D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY140D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY140D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY160D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY160D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY180D60': 'Reijnders Graveer & Lasertechniek BV',
  'BNESSULGY180D80': 'Reijnders Graveer & Lasertechniek BV',
  'BNEBUC': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBULH': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEBB': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEBB6018': 'Dutch Design Productions BV - Tristan Frencken',
  'ZZZ_PRO_Computerbril': 'bol.com B.V.',
  'ZZZ_ARMS_HB00BT-BLK Bolt througy no hub': 'Adapt Deutschland GmbH',
  'ZZZ_Brio Ultra HD PRO Zakelijke webcam': 'Micro-Mail Zeewolde B.V.',
  'BNECA6O': 'Kelly International Corp.',
  'BNECA7': 'Hoolin Research Co. Ltd.',
  'BNECA7D': 'Hoolin Research Co. Ltd.',
  'BNECA7G': 'Hoolin Research Co. Ltd.',
  'BNECA7GM': 'Hoolin Research Co. Ltd.',
  'BNECA8': 'Kelly International Corp.',
  'SSCKAB': 'B15 Engineering',
  'ZZZ_Arms_Kabelgeleiding Galaxy post': 'Fellowes Holdings B.V.',
  'BNECAP8106BFBH': 'Flokk BV',
  'BNECAP8106BFSH': 'Flokk BV',
  'BNECAP8106BFSS': 'Flokk BV',
  'ZZZ_CHAIR_00WWDK': 'Flokk BV',
  'ZZZ_CHAIR_CAP8126BFSS_00WYTM': 'Flokk BV',
  'BNECAPZR20H': 'Flokk BV',
  'BNECAPZR20Z': 'Flokk BV',
  'BNECAPZR19H': 'Flokk BV',
  'BNECAPZR19Z': 'Flokk BV',
  'BNECAPHR': 'Flokk BV',
  'BNECAPRRH': 'Flokk BV',
  'BNECAPRR': 'Flokk BV',
  'BNECAPG150': 'Flokk BV',
  'BNECAPDS': 'Flokk BV',
  'BNECAPFSBB': 'Flokk BV',
  'BNECAPFSBPA': 'Flokk BV',
  'BNECAPG265': 'Flokk BV',
  'BNECAPFR': 'Flokk BV',
  'BNECAPSU': 'Flokk BV',
  'BNECAPTLC': 'Flokk BV',
  'ZZZ_Chair_CAP8020_0E3VII': 'Flokk BV',
  'BNECAPPG150': 'Flokk BV',
  'BNECAPPG265': 'Flokk BV',
  'BNECAPPFSBB': 'Flokk BV',
  'BNECAPPFSBA': 'Flokk BV',
  'BNECAPPFR': 'Flokk BV',
  'BNECAPPSU': 'Flokk BV',
  'BNECAPPTLC': 'Flokk BV',
  'BNECAPPZFP': 'Flokk BV',
  'BNECAPPZRFP': 'Flokk BV',
  'BNECAPPZSP': 'Flokk BV',
  'BNECAPPZRSP': 'Flokk BV',
  'ZZZ_CHAIRS_BNECAPP8010_0HB1RC': 'Flokk BV',
  'BNECAPZ': 'Flokk BV',
  'BNECAPZRH': 'Flokk BV',
  'BNECAPZR': 'Flokk BV',
  'ZZZ_PRO_CBDLSControlbox 2 channels': 'LINAK Actuator-Systems BV',
  'BNEC810US': 'ZIPPY Technology Corp.',
  'BNEC830BE': 'ZIPPY Technology Corp.',
  'BNEC830DE': 'ZIPPY Technology Corp.',
  'BNECMW2310': 'ALSO Nederland B.V.',
  'BNECPSGRNLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNETSS960GL': 'Targus Europe Ltd',
  'BNETSB938GL': 'Targus Europe Ltd',
  'BNETBT919GL': 'Targus Europe Ltd',
  'BNETSB937GL': 'Targus Europe Ltd',
  'BNECDOC440': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEFRB90': 'MeySystems GmbH',
  'BNECR': 'Dutch Design Productions BV - Tristan Frencken',
  'BNECR10': 'Dutch Design Productions BV - Tristan Frencken',
  'BNECBK': 'Intronics',
  'BNECKSQ': '"Shenzhen SQT Electronics Co., Ltd."',
  'ZZZ_Complet Headrest HAG Capisco 8106': 'Flokk BV',
  'RM-AS-RED': 'Copaco Nederland B.V.',
  'ZZZ_PRO_CTR-CDWRRED00110': 'Copaco Nederland B.V.',
  'ZZZ_CDRMRED10110': 'Copaco Nederland B.V.',
  'PS-PLUS': 'Copaco Nederland B.V.',
  'PS-PLUS-EXT': 'Copaco Nederland B.V.',
  'RM-MOBILE': 'Copaco Nederland B.V.',
  'RM-RED': 'Copaco Nederland B.V.',
  'RM-RED-MAX': 'Copaco Nederland B.V.',
  'RM-RED-PLUS': 'Copaco Nederland B.V.',
  'RM-RED-PLUS-WL': 'Copaco Nederland B.V.',
  'RM-RED-WL': 'Copaco Nederland B.V.',
  'UNIMOUSE': 'Copaco Nederland B.V.',
  'UNIMOUSE-WL': 'Copaco Nederland B.V.',
  'UNIMOUSE-WL-L': 'Copaco Nederland B.V.',
  'UNIMOUSE-L': 'Copaco Nederland B.V.',
  'BNECONW32': 'Flokk BV',
  'ACEA': 'Reijnders Graveer & Lasertechniek BV',
  'ACEAS': 'Reijnders Graveer & Lasertechniek BV',
  'BNECPUFIX': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNECPUFIXR': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNECPUFIXR65': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNECRDA3D': 'Flokk BV',
  'BNECRDVR': 'Flokk BV',
  'BNECRDAA': 'Flokk BV',
  'BNECRDG200': 'Flokk BV',
  'BNECRDG265': 'Flokk BV',
  'BNECRDSU': 'Flokk BV',
  'BNECRDSB': 'Flokk BV',
  'BNECRDHS': 'Flokk BV',
  'BNECRDVSGA': 'Flokk BV',
  'BNECRD6003B3DH': 'Flokk BV',
  'BNECRD6003B3DS': 'Flokk BV',
  'BNECRDHG5H': 'Flokk BV',
  'BNECRDHV6': 'Flokk BV',
  'BNECRDMG3': 'Flokk BV',
  'BNECRDMV4': 'Flokk BV',
  'BNECRDSV71': 'Flokk BV',
  'BNECRDV72': 'Flokk BV',
  'BNECRDHVS6': 'Flokk BV',
  'BNECRDLV2': 'Flokk BV',
  'BNECRD05BFB3DS': 'Flokk BV',
  'BNECRD03BFB3DS': 'Flokk BV',
  'BNEDFWKMS': 'Health2Work',
  'ZZZ_PRO_DPF1M00-010006-914759': 'LINAK Actuator-Systems BV',
  'BNEDBL185': 'Worktrainer',
  'BNEDBM165': 'Worktrainer',
  'ZZZ_DeskbikeMediumWhite': 'Worktrainer',
  'DIENST': 'BakkerElkhuizen B.V.',
  'BNEDOCK340': 'Magic Control Technologie Corp.',
  'ERGO1600': 'Reijnders Graveer & Lasertechniek BV',
  'ERGO1500': 'Reijnders Graveer & Lasertechniek BV',
  'ERGO1700': 'Reijnders Graveer & Lasertechniek BV',
  'BNEDR': 'Matting AB',
  'ZZZ_ARMS_DopGalaxyPost': 'Fellowes Holdings B.V.',
  '"ZZZ_ARMS_Double Spacearm QC': 'GM Mount Bl",Adapt Deutschland GmbH',
  'DPROEU': 'Entiris',
  'BNEDLPRM': 'Tapir BV',
  'BNEDLTFT': '3M Nederland',
  'BNESPDSLPBT': 'Adapt Deutschland GmbH',
  'BNESPDSLPGR': 'Adapt Deutschland GmbH',
  'BNESPDSLPCL': 'Adapt Deutschland GmbH',
  'BNESPDSLPLOBT': 'Adapt Deutschland GmbH',
  'BNESPDSLPLOGR': 'Adapt Deutschland GmbH',
  'BNESPDSLPLOCL': 'Adapt Deutschland GmbH',
  'BNESPDSLPSHBT': 'Adapt Deutschland GmbH',
  'BNESPDSLPSHGR': 'Adapt Deutschland GmbH',
  'BNESPDSLPSHCL': 'Adapt Deutschland GmbH',
  'BNEDB4558': 'Score BV',
  'BNEDXT': 'Morgan Maxwell Ltd',
  'BNEDXTW': 'Morgan Maxwell Ltd',
  'BNEDXTWR': 'Morgan Maxwell Ltd',
  'BNEDXT3': 'Morgan Maxwell Ltd',
  'BNEDXT3W': 'Morgan Maxwell Ltd',
  'BNEDXT3WR': 'Morgan Maxwell Ltd',
  'BNEEMFA4': 'De Vos Ergonomics BV',
  'BNEEBL': 'We Fabricate B.V.',
  'BNEEBLAUP': 'We Fabricate B.V.',
  'BNEEBLUSP': 'We Fabricate B.V.',
  'BNEEB4558': 'Score BV',
  'BNEEMK': 'Feida Corporation Ltd',
  'BNEEDDE': 'Vierpool BV',
  'BNEEDUK': 'Vierpool BV',
  'BNEEDUS': 'Vierpool BV',
  'BNEEGK': 'Backshop BV',
  'BNEEMDW': 'Health2Work',
  'BNEQ160DG': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQ220': 'Unfolding BV          FAILLIET',
  'BNEQ26012': 'Unfolding BV          FAILLIET',
  'BNEQ260DL': 'Unfolding BV          FAILLIET',
  'BNEQ260HP': 'Unfolding BV          FAILLIET',
  'BNEQ260ITI': 'Unfolding BV          FAILLIET',
  'BNEQ260': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQ260OFMIX': 'Unfolding BV          FAILLIET',
  'BNEQ260SECU': 'Unfolding BV          FAILLIET',
  'BNEQ260STAPLES': 'Unfolding BV          FAILLIET',
  'BNEQ330FEET': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQ330': 'Timmerije BV',
  'BNEQ330C': 'Timmerije BV',
  'BNEQHPDG': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQH': 'Unfolding BV          FAILLIET',
  'BNEES': 'Backshop BV',
  'BNEESLB': '"Fersgo Co., Ltd."',
  'BNEESLWR': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNEESLDG': '"Fersgo Co., Ltd."',
  'BNEUASEA': '"Fersgo Co., Ltd."',
  'BNEESLWRB': '"Fersgo Co., Ltd."',
  'BNET320': 'Reijnders Graveer & Lasertechniek BV',
  'BNET340': 'Entiris',
  'BNET350': 'Ooxy Technology Ltd.',
  'BNETOP320CGRN': 'Reijnders Graveer & Lasertechniek BV',
  'BNETOP320CLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNETOP320': 'Reijnders Graveer & Lasertechniek BV',
  'BNEET': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEEVWDC': 'Evoluent',
  'BNEEVCK': 'Evoluent',
  'BNEEVRDL': 'Evoluent',
  'BNEEVRDLW': 'Evoluent',
  'BNEEVRD': 'Evoluent',
  'BNEEVRDW': 'Evoluent',
  'BNEEVRDS': 'Evoluent',
  'BNEEVRDSW': 'Evoluent',
  'BNEEVKDE': 'Evoluent',
  'BNEEVK': 'Evoluent',
  'BNEEVRC': 'Evoluent',
  'BNEEVRCW': 'Evoluent',
  'BNEEVRCWG': 'Evoluent',
  'BNEEVSR': 'Evoluent',
  'BNEEWCMP': 'Evoluent',
  'BNEEVR': 'Evoluent',
  'BNEEVWD': 'Evoluent',
  'BNEEVL4': 'Evoluent',
  'BNEEVR4': 'Evoluent',
  'BNEEVR4BB': 'Evoluent',
  'BNEEVR4S': 'Evoluent',
  'BNEEVR4SW': 'Evoluent',
  'BNEEVR4WB': 'Evoluent',
  'BNEEVR4W': 'Evoluent',
  'BNEEVWD4': 'Evoluent',
  'BNEEVWDD': 'Evoluent',
  'ZZZ_Chairs_Extra hoge gaslift 265 mm Zwa': 'Flokk BV',
  'BNEFF3MVM': '"Shenzhen Loyal Electronics Co., Ltd"',
  'BNEFFP3MVM': '"Shenzhen Loyal Electronics Co., Ltd"',
  'BNEF681013': 'Fellowes Holdings B.V.',
  'BNEF681015': 'In2Brands BV',
  'BNEF681018': 'Fellowes Holdings B.V.',
  'BNEF80756': 'Fellowes Holdings B.V.',
  'BNEF80753': 'Fellowes Holdings B.V.',
  'BNEF80799': 'In2Brands BV',
  'BNEF809133': 'Fellowes Holdings B.V.',
  'BNEF80776': 'In2Brands BV',
  'BNEF80777': 'In2Brands BV',
  'BNEF80779': 'In2Brands BV',
  'BNEF80780': 'In2Brands BV',
  'BNEF80781': 'In2Brands BV',
  'BNEF80765': 'Fellowes Holdings B.V.',
  'BNEF80766': 'Fellowes Holdings B.V.',
  'BNEFG809525': 'In2Brands BV',
  'BNEFG809524': 'In2Brands BV',
  'BNEFG809523': 'In2Brands BV',
  'ZZZ_ARMS_BNEFG820003-S': 'Fellowes Holdings B.V.',
  'BNEFG809455': 'In2Brands BV',
  'BNEFG809454': 'In2Brands BV',
  'BNEFG809453': 'In2Brands BV',
  'BNEFG809456': 'In2Brands BV',
  'BNEFG809457': 'In2Brands BV',
  'BNEFG809458': 'In2Brands BV',
  'BNEFG809469': 'In2Brands BV',
  'BNEFG809468': 'In2Brands BV',
  'BNEFG809467': 'In2Brands BV',
  'BNEFG809446': 'In2Brands BV',
  'BNEFG809448': 'In2Brands BV',
  'BNEFG809447': 'In2Brands BV',
  'BNEFG809452': 'In2Brands BV',
  'BNEFG809451': 'In2Brands BV',
  'BNEFG810052-S': 'In2Brands BV',
  'BNEFG810051-S': 'In2Brands BV',
  'BNEFG810050-S': 'In2Brands BV',
  'BNEFG809522': 'In2Brands BV',
  'BNEFG809521': 'In2Brands BV',
  'BNEFG809520': 'In2Brands BV',
  'BNEFG809450': 'In2Brands BV',
  'BNEFG809462': 'In2Brands BV',
  'BNEFG809461': 'In2Brands BV',
  'BNEFG809460': 'In2Brands BV',
  'ZZZ_ARMS_BNEFG809544': 'Fellowes Holdings B.V.',
  'ZZZ_ARMS_BNEFG809545': 'Fellowes Holdings B.V.',
  'BNEFG809486': 'In2Brands BV',
  'ZZZ_ARMS_BNEFG809509': 'Fellowes Holdings B.V.',
  'BNEFG810037-S': 'In2Brands BV',
  'BNEFG810036-S': 'In2Brands BV',
  'BNEFG810035-S': 'In2Brands BV',
  'BNEFG810210-S': 'In2Brands BV',
  'BNEFG810005-S': 'In2Brands BV',
  'BNEFG810004-S': 'In2Brands BV',
  'BNEFG810003-S': 'In2Brands BV',
  'BNEFG810028-S': 'In2Brands BV',
  'BNEFG809492': 'In2Brands BV',
  'BNEFG809491': 'In2Brands BV',
  'BNEFG809490': 'In2Brands BV',
  'BNEFG809497': 'In2Brands BV',
  'BNEFG809496': 'In2Brands BV',
  'BNEFG809495': 'In2Brands BV',
  'BNEFG809427-S': 'In2Brands BV',
  'BNEFG809415-S': 'In2Brands BV',
  'BNEFG809428-S': 'In2Brands BV',
  'BNEFG809426-S': 'In2Brands BV',
  'BNEFG809426-SN': 'In2Brands BV',
  'BNEFG810027-S': 'In2Brands BV',
  'BNEFG810026-S': 'In2Brands BV',
  'BNEFG810025-S': 'In2Brands BV',
  'BNEFG809498': 'In2Brands BV',
  'ZZZ_ARMS_BNEFG820004-S': 'Fellowes Holdings B.V.',
  'BNEFG809422': 'In2Brands BV',
  'BNEFG809421': 'In2Brands BV',
  'BNEFG809420': 'In2Brands BV',
  'BNEFG809476': 'In2Brands BV',
  'BNEFG809416': 'In2Brands BV',
  'BNEFG809416-S': 'In2Brands BV',
  'BNEFG809475': 'In2Brands BV',
  'BNEFG809478': 'In2Brands BV',
  'BNEFG809478OLD': 'In2Brands BV',
  'BNEFG809417': 'In2Brands BV',
  'BNEFG809417-S': 'In2Brands BV',
  'BNEFG809477': 'In2Brands BV',
  'BNEFG809412': 'In2Brands BV',
  'BNEFG809432': 'In2Brands BV',
  'BNEFG809431': 'In2Brands BV',
  'BNEFG809430': 'In2Brands BV',
  'BNEFG809411': 'In2Brands BV',
  'BNEFG809410': 'In2Brands BV',
  'ZZZ_ARMS_BNEFG820001-S': 'Fellowes Holdings B.V.',
  'ZZZ_ARMS_BNEFG820002-S': 'Fellowes Holdings B.V.',
  'BNEFG809445': 'In2Brands BV',
  'BNEFG809444': 'In2Brands BV',
  'BNEFG809443': 'In2Brands BV',
  'BNEFG809442': 'In2Brands BV',
  'BNEFG809441': 'In2Brands BV',
  'BNEFG809440': 'In2Brands BV',
  'BNEFG809485': 'In2Brands BV',
  'BNEFG809484': 'In2Brands BV',
  'BNEFG809483': 'In2Brands BV',
  'BNEFG810024-S': 'In2Brands BV',
  'BNEFG810023-S': 'In2Brands BV',
  'BNEFG810022-S': 'In2Brands BV',
  'BNEFG809493-S': 'In2Brands BV',
  'BNEFG809449-S': 'In2Brands BV',
  'BNEFG809494-S': 'In2Brands BV',
  'BNEFG809542': 'In2Brands BV',
  'BNEFG809541-S': 'In2Brands BV',
  'BNEFG809540': 'In2Brands BV',
  'BNEFG810002-S': 'In2Brands BV',
  'BNEFG810001-S': 'In2Brands BV',
  'BNEFG810000-S': 'In2Brands BV',
  'BNEFG810008-S': 'In2Brands BV',
  'BNEFG810007-S': 'In2Brands BV',
  'BNEFG810006-S': 'In2Brands BV',
  'BNEFG810011-S': 'In2Brands BV',
  'BNEFG810010-S': 'In2Brands BV',
  'BNEFG810009-S': 'In2Brands BV',
  'BNEFG809548': 'In2Brands BV',
  'BNEFG809547': 'In2Brands BV',
  'BNEFG809546': 'In2Brands BV',
  'BNEFG810081-S': 'In2Brands BV',
  'BNEFG810080-S': 'In2Brands BV',
  'BNEFG809517': 'In2Brands BV',
  'BNEFG809516': 'In2Brands BV',
  'BNEFG809482': 'In2Brands BV',
  'BNEFG809481': 'In2Brands BV',
  'BNEFG809480': 'In2Brands BV',
  'BNEFG809472': 'In2Brands BV',
  'BNEFG809471': 'In2Brands BV',
  'BNEFG809470': 'In2Brands BV',
  'BNEFG809512': 'In2Brands BV',
  'BNEFG809511': 'In2Brands BV',
  'BNEFG809510': 'In2Brands BV',
  'BNEFG809538': 'In2Brands BV',
  'BNEFG809537': 'In2Brands BV',
  'BNEFG809536': 'In2Brands BV',
  'BNEFG809508': 'In2Brands BV',
  'BNEFG810055-S': 'In2Brands BV',
  'BNEFG810054-S': 'In2Brands BV',
  'BNEFG810053-S': 'In2Brands BV',
  'BNEFG809507': 'In2Brands BV',
  'BNEFG809506': 'In2Brands BV',
  'BNEFG810020-S': 'In2Brands BV',
  'BNEFG810019-S': 'In2Brands BV',
  'BNEFG810018-S': 'In2Brands BV',
  'BNEFG810017-S': 'In2Brands BV',
  'BNEFG810016-S': 'In2Brands BV',
  'BNEFG810015-S': 'In2Brands BV',
  'BNEFG810021-S': 'In2Brands BV',
  'BNEFG809505': 'In2Brands BV',
  'BNEFG809499': 'In2Brands BV',
  'BNEFG809504': 'In2Brands BV',
  'BNEFG809438': 'In2Brands BV',
  'BNEFG809502': 'In2Brands BV',
  'BNEFG809501': 'In2Brands BV',
  'BNEFG809500': 'In2Brands BV',
  'BNEFG809466': 'In2Brands BV',
  'BNEFG809465': 'In2Brands BV',
  'BNEFG809464': 'In2Brands BV',
  'BNEFG809503': 'In2Brands BV',
  'BNEF681052': 'In2Brands BV',
  'BNEF681062': 'In2Brands BV',
  'BNEF681059': 'In2Brands BV',
  'BNEF681058': 'In2Brands BV',
  'BNEF681055': 'In2Brands BV',
  'BNEF681054': 'In2Brands BV',
  'BNEF681057': 'In2Brands BV',
  'BNEF681056': 'In2Brands BV',
  'BNEF681061': 'In2Brands BV',
  'BNEF681060': 'In2Brands BV',
  'BNEF681076': 'In2Brands BV',
  'BNEF681016': 'In2Brands BV',
  'BNEF681095': 'In2Brands BV',
  'BNEF681017': 'In2Brands BV',
  'BNEF681008': 'In2Brands BV',
  'BNEF681025': 'In2Brands BV',
  'BNEF681026': 'In2Brands BV',
  'BNEF681010': 'In2Brands BV',
  'ZZZ_BNEF12021': 'Fellowes Holdings B.V.',
  'ZZZ_ARMS_80763': 'Fellowes Holdings B.V.',
  'BNEF141988': 'In2Brands BV',
  'BNEFG80972': 'In2Brands BV',
  'BNEFG80971': 'In2Brands BV',
  'BNEFG80973': 'In2Brands BV',
  'ZZZ_ARMS_BNEF80775': 'Fellowes Holdings B.V.',
  'ZZZ_ARMS_BNEF681142-UK': 'Fellowes Holdings B.V.',
  'BNEF681041': 'Fellowes Holdings B.V.',
  'ZZZ_ARMS_BNEF681041': 'Fellowes Holdings B.V.',
  'ZZZ_ARMS_BNEF681134-UK': 'Fellowes Holdings B.V.',
  'BNEFAS1330': '3M Nederland',
  'ERGO2000': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFDESK630N': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEFDESK640CR': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEFDESK640': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEFDESK640A': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFDCGRN': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFDCLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFDCCA4': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFDCC': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFDWS': 'Reijnders Graveer & Lasertechniek BV',
  'ZZZ_Flexible White': 'CMG-Global Limited and/or CMG (Ningbo) Electroacoustic Technology Corporation',
  'BNEFT170DG': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFT27012': 'Unfolding BV          FAILLIET',
  'BNEFT270': 'Reijnders Graveer & Lasertechniek BV',
  'BNEFTO': 'Hulshof business cases BV',
  'ZZZ_ARMS_80981': 'Fellowes Holdings B.V.',
  'BNEFFD': 'Flokk BV',
  'BNEFFSL': 'Flokk BV',
  'BNEFBA': 'Health2Work',
  'ZZZ_FOOTREST EFS 90 ESD': 'MeySystems GmbH',
  'BNEFRN1': 'We R Asia B.V.',
  'BNEFRN2': 'We R Asia B.V.',
  'BNEFRN3': 'IFG Industrial Foams B.V.',
  'BNEFRIIUS': 'Backshop BV',
  'BNEFRIINUM': 'Backshop BV',
  'BNEFRS20US': 'Backshop BV',
  'BNEFRIIVIP': 'Backshop BV',
  'BNEFUT1100SB3DH': 'Flokk BV',
  'BNEFUT1100SB3DS': 'Flokk BV',
  'BNEFUT1200SB3DH': 'Flokk BV',
  'BNEFUT1200SB3DS': 'Flokk BV',
  'BNEFUT11SBFBL3DH': 'Flokk BV',
  'BNEFUT11SBFBL3DS': 'Flokk BV',
  'BNEFUT12SBFB3DH': 'Flokk BV',
  'BNEFUT12SBFB3DS': 'Flokk BV',
  'BNEFUT12SBFG3DH': 'Flokk BV',
  'BNEFUT12SBFG3DS': 'Flokk BV',
  'ZZZ_CHAIRS_FUT1100SSF_0155DT': 'Flokk BV',
  'BNEFUT': 'Flokk BV',
  'BNEFUTM': 'Flokk BV',
  'BNEFUTMS': 'Flokk BV',
  'BNEFUTSL': 'Flokk BV',
  'BNEFUTG200': 'Flokk BV',
  'BNEFUTAR': 'Flokk BV',
  'BNEFUTFSBA': 'Flokk BV',
  'BNEFUTFSBP': 'Flokk BV',
  'BNEFUTFR': 'Flokk BV',
  'BNEFUTLS': 'Flokk BV',
  'BNEFUTAR3D': 'Flokk BV',
  'BNEFUTARLT': 'Flokk BV',
  'ZZZ_ARMS_809458EL': 'Fellowes Holdings B.V.',
  'TICKEN': 'Ticken BV',
  'TICKENSUB': 'Ticken BV',
  'TICKENEX': 'Ticken BV',
  'BNEGWP50': '3M Nederland',
  'BNEGWP70': '3M Nederland',
  'BNEGS2.5M': 'KabelDirect',
  'BNEGS25M': 'KabelDirect',
  'BNEGF3534029B4DH': 'Flokk BV',
  'BNEGF3534029B4DS': 'Flokk BV',
  'BNEGF643578B4DH': 'Flokk BV',
  'BNEGF643578B4DS': 'Flokk BV',
  'ZZZ_Chair_Giro64_0BNWJC': 'Flokk BV',
  'ZZZ_Chairs_GiroFlex 64-3578_0NU4KD': 'Flokk BV',
  'ZZZ_Chairs_GiroFlex 64-3578_0NU4N7': 'Flokk BV',
  'ZZZ_Chairs_GiroFlex 64-3578_0NU4Q3': 'Flokk BV',
  'ZZZ_Chairs_GiroFlex 64-3578_0NU4GM': 'Flokk BV',
  'BNEGTBMACUS': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTBDE': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTBDK': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTBFR': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTBUK': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTBUS': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEBNUM': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEBDE': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEBFR': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEBUK': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEBUS': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEML': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEMR': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTEMRB': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTBNUM': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTBNUMMAC': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTWNUM': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTTSP': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTTAR': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTTBUK': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTTBUS': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTTDE': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTTUK': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTTUS': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGTWR': '"Key Ovation, LLC dba Goldtouch"',
  'BNEGM': 'Ooxy Technology Ltd.',
  'BNEGMW': 'Ooxy Technology Ltd.',
  'BNEGPWVM': 'Master Electronic Technology Co. Ltd.',
  'ZZZ_ARMS_HB00GM-BLK Grommet mount only': 'Adapt Deutschland GmbH',
  'BNEH05VH': 'Flokk BV',
  'BNEH05GH': 'Flokk BV',
  'BNEH05VL': 'Flokk BV',
  'BNEH05GL': 'Flokk BV',
  'BNEH05VM': 'Flokk BV',
  'BNEH05GM': 'Flokk BV',
  'BNEH05G200': 'Flokk BV',
  'BNEH05G265': 'Flokk BV',
  'BNEH05ART': 'Flokk BV',
  'BNEH05DS': 'Flokk BV',
  'BNEH05FSBA': 'Flokk BV',
  'BNEH05FR': 'Flokk BV',
  'BNEH05SU': 'Flokk BV',
  'BNEH05HRF': 'Flokk BV',
  'BNEH05HRP': 'Flokk BV',
  'BNEH05A3D': 'Flokk BV',
  'BNEH05ALT': 'Flokk BV',
  'ZZZ_Chairs_Capisco8106_019AH7': 'Flokk BV',
  'ZZZ_CHAIRS_CapiscoPulse8010_OH7EC1': 'Flokk BV',
  'ZZZ_Chairs_CapiscoPuls8020_OE3BNS': 'Flokk BV',
  'ZZZ_Chairs_CapiscoPuls 8020_OE12KE': 'Flokk BV',
  'ZZZ_Chairs_CapiscoPulse 8020_OJB8LD': 'Flokk BV',
  'ZZZ_Chairs_Capisco8106Seating_FM66061': 'Flokk BV',
  'BNEHG150S': 'Flokk BV',
  'BNEHG150B': 'Flokk BV',
  'BNEHG200S': 'Flokk BV',
  'BNEHG200B': 'Flokk BV',
  'BNEHG200BFUT': 'Flokk BV',
  'BNEHG265S': 'Flokk BV',
  'BNEHG265B': 'Flokk BV',
  'BNEHZW': 'Flokk BV',
  'BNEUGV': 'Flokk BV',
  'BNEZZW': 'Flokk BV',
  'BNEHS3MVML': 'Roma Technology Co. Ltd',
  'BNEHS3MVMR': 'Roma Technology Co. Ltd',
  'BNESRML': 'Ooxy Technology Ltd.',
  'BNESRMLW': 'Ooxy Technology Ltd.',
  'BNESRMR': 'Ooxy Technology Ltd.',
  'BNESRMRVS5': 'Backshop BV',
  'BNESRMW': 'Ooxy Technology Ltd.',
  'BNESRMRWVS5': 'Backshop BV',
  'ZZZ_PRO_BNEPH_Cable': 'Hippus NV / Handshoemouse',
  'BNEP210L': 'Hippus NV / Handshoemouse',
  'BNEP210LW': 'Hippus NV / Handshoemouse',
  'BNEP190L': 'Hippus NV / Handshoemouse',
  'BNEP190LW': 'Hippus NV / Handshoemouse',
  'BNEP170L': 'Hippus NV / Handshoemouse',
  'BNEP170LW': 'Hippus NV / Handshoemouse',
  'BNEP150R': 'Hippus NV / Handshoemouse',
  'ZZZ_PRO_BNEP150RXS': 'Ergo2Work BV',
  'BNEP210R': 'Hippus NV / Handshoemouse',
  'BNEP210RW': 'Hippus NV / Handshoemouse',
  'BNEP190R': 'Dexin Corporation',
  'BNEP190RW': 'Hippus NV / Handshoemouse',
  'BNEP170R': 'Hippus NV / Handshoemouse',
  'BNEP170RW': 'Dexin Corporation',
  'BNEPS210RLW': 'Hippus NV / Handshoemouse',
  'BNEPS190RLW': 'Hippus NV / Handshoemouse',
  'BNEPS170RLW': 'Hippus NV / Handshoemouse',
  'BNEPHWR': 'Hippus NV / Handshoemouse',
  'BNEHFBO': 'TwoWork Partner in Interieurprojecten B.V.',
  'BNEHFOO': 'TwoWork Partner in Interieurprojecten B.V.',
  'BNEHFWW': 'TwoWork Partner in Interieurprojecten B.V.',
  'BNEBOXC': 'BakkerElkhuizen International B.V.',
  'BNEBOXL': 'Drukland',
  'BNELINHCBP': 'LINAK Actuator-Systems BV',
  'BNEHCDTB': 'Ooxy Technology Ltd.',
  'BNEHCDTWH': 'Ooxy Technology Ltd.',
  'BNEHCT': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEHCTBBE': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEHCTBMA': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEHCTBOA': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEHCTBWH': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSDB155': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSDG155': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTBE100': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTBE120': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTBE140': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTBE160': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTBE180': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTBE200': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTMA100': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTMA120': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTMA140': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTMA160': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTMA180': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTMA200': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTOA100': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTOA120': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTOA140': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTOA160': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTOA180': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTOA200': 'Dutch Design Productions BV - Tristan Frencken',
  'BNESSTOA200': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTWH100': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTWH120': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTWH140': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTWH160': 'MultiDesk Productie B.V.',
  'BNEIQSSTWH180': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEIQSSTWH200': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEJBBB': 'Bota NV',
  'BNEJHRGL': 'Bota NV',
  'BNEJZS': 'Bota NV',
  'BNEJZWVEB': 'Bota NV',
  'BNEJUMHB': 'Score BV',
  'BNEJUMHF': 'Score BV',
  'BNEJUMHT': 'Score BV',
  'BNEJUMHTL': 'Score BV',
  'BNEJUMLB': 'Score BV',
  'BNEJUMLF': 'Score BV',
  'BNEJUMLT': 'Score BV',
  'BNEJUMNB': 'Score BV',
  'BNEJUMNF': 'Score BV',
  'BNEJUMNT': 'Score BV',
  'BNEJUMNTL': 'Score BV',
  'ZZZ_ARMS_Kabelslang 130 cm': 'Fellowes Holdings B.V.',
  'BNEKABUSII': 'Kinesis Corporation',
  'BNEDLBP114': 'Thule Organization Solutions BV',
  'BNETCG660GL': 'Targus Europe Ltd',
  'BNETCG670GL': 'Targus Europe Ltd',
  'BNETSB949EU': 'Targus Europe Ltd',
  'BNETSB944EU': 'Targus Europe Ltd',
  'BNERBP217': 'Thule Organization Solutions BV',
  'BNERBP315': 'Thule Organization Solutions BV',
  'BNEZLCS214': 'Thule Organization Solutions BV',
  'BNEPNC216': 'Thule Organization Solutions BV',
  'BNEPNC218': 'Thule Organization Solutions BV',
  'BNETCG655EU': 'Targus Europe Ltd',
  'BNETCG660EU': 'Targus Europe Ltd',
  'BNETCG670EU': 'Targus Europe Ltd',
  'BNETSB915EU': 'Targus Europe Ltd',
  'BNETCG717': 'Targus Europe Ltd',
  'BNETR15': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEZLRS217': 'Thule Organization Solutions BV',
  'BNETBT916EU': 'Targus Europe Ltd',
  'BNETSB700EU': 'Targus Europe Ltd',
  'BNELSBASIC': 'Timmerije BV',
  'BNECT1314BDO': 'Targus Europe Ltd',
  'BNECT1314': 'Targus Europe Ltd',
  'BNETCG455EU': 'Targus Europe Ltd',
  'BNETCG460EU': 'Targus Europe Ltd',
  'BNETCG470EU': 'Targus Europe Ltd',
  'BNETBR022EU': 'Targus Europe Ltd',
  'BNELMD': 'VSO Technology(HK) Co. Ltd',
  'ZZZ_PRO_LGUG34GP63AP-B': 'bol.com B.V.',
  'BNELINBLE2': 'LINAK Actuator-Systems BV',
  'BNELINUSB2': 'LINAK Actuator-Systems BV',
  'BNELINDPH': 'LINAK Actuator-Systems BV',
  'ZZZ_PROJECT_LOD_61x42x58': 'TwoWork Partner in Interieurprojecten B.V.',
  'BNELCASECYG': 'Dutch Design Productions BV - Tristan Frencken',
  'BNELLPRCMUSB': 'LogicData',
  'BNELM500S': 'Ingram Micro BV',
  'BNELM705': 'Ingram Micro BV',
  'BNELM105': 'Ingram Micro BV',
  'BNELM500': 'Ingram Micro BV',
  'BNELTMM': 'Ingram Micro BV',
  'BNELM185G': 'Dustin Netherlands B.V.',
  'BNELMK520': 'Ingram Micro BV',
  'BNELM170': 'Ingram Micro BV',
  'BNELM560': 'Ingram Micro BV',
  'BNEM570': 'Ingram Micro BV',
  'BNEM575': 'Ingram Micro BV',
  'ZZZ_PROJECT_Los doek-stoffering': 'Deblick B.V.',
  'BNEM870BDE': '"Digimore Electronics Co., Ltd"',
  'BNEM870BFR': '"Digimore Electronics Co., Ltd"',
  'BNEM870BNOR': '"Digimore Electronics Co., Ltd"',
  'BNEM870BUS': '"Digimore Electronics Co., Ltd"',
  'ZZZ_Chairs_160.054 McKenzie Lendenrol Sl': 'Ergo2Work BV',
  'BNETMCKNZRK': 'Backshop BV',
  'BNEMNEK': 'TD SYNNEX Netherlands B.V',
  'BNEMW3MVML': '"Shenzhen Keyceo Tech Co.,Limited"',
  'BNEMW3MVMR': '"Shenzhen Keyceo Tech Co.,Limited"',
  'BNEMPEE': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEMP': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEMPD': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEMP1003': 'Dutch Design Productions BV - Tristan Frencken',
  'ERGO4000': 'Reijnders Graveer & Lasertechniek BV',
  'MS150': 'Reijnders Graveer & Lasertechniek BV',
  'ZZZ_PROJECT_MONTAGE': 'Deblick B.V.',
  'BNEMSTA': 'Mousetrapper AB',
  'BNEMSTAT': 'Mousetrapper AB',
  'BNEMSTALPHA': 'Backshop BV',
  'BNEMTAR': 'Mousetrapper AB',
  'BNEMSTF': 'Mousetrapper AB',
  'BNEMSTFW': 'Mousetrapper AB',
  'BNEMSTL': 'Mousetrapper AB',
  'BNEMSTLR': 'Mousetrapper AB',
  'BNEMST': 'Mousetrapper AB',
  'BNEMSTP': 'Mousetrapper AB',
  'MPROEU': 'Timmerije BV',
  'BNETSB94501GL': 'Targus Europe Ltd',
  'BNETSB948GL': 'Targus Europe Ltd',
  'BNENT3LWR': 'Backshop BV',
  'BNENT3MR': 'Backshop BV',
  'BNENT3MWL': 'Backshop BV',
  'BNENT3MWR': 'Backshop BV',
  'BNENT3SWR': 'Backshop BV',
  'ZZZ_Chairs_Offecct Phoenix': 'Flokk BV',
  'BNEWO2S': 'ALSO Nederland B.V.',
  'ONTWUS': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEOYM': 'Ergoption AB / Kenson AB',
  'BNEOYML': 'Ergoption AB / Kenson AB',
  'BNEOYMW': 'Ergoption AB / Kenson AB',
  'BNEOYMWL': 'Ergoption AB / Kenson AB',
  'BNEOYMWR': 'Ergoption AB / Kenson AB',
  'BNEPELS': 'Reijnders Graveer & Lasertechniek BV',
  'BNEPT': 'doosopmaat.nl',
  'BNEPCC': 'Penclic AB',
  'BNEPCW': 'Penclic AB',
  'BNEPVML': 'Health2Work',
  'BNEPVMM': 'Health2Work',
  'BNEPVMS': 'Health2Work',
  'ZZZ_PROJECT_Plafondspots': 'Deblick B.V.',
  'BNEPCTB': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEPCTF': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEPCTG': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEPCTI': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEPCTJ': 'Dutch Design Productions BV - Tristan Frencken',
  'ZZZ_ARMS_PowerDeskUp 1.0': 'Fellowes Holdings B.V.',
  'ZZZ_ARM_681069FR': 'In2Brands BV',
  'BNEPS3TF': 'Comatters BV',
  'BNEPS4TF': 'Comatters BV',
  'ZZZ_ARMS_681108': 'Fellowes Holdings B.V.',
  'BNEPODBA': 'In2Brands BV',
  'BNEPODBCB': 'In2Brands BV',
  'BNEPODBCW': 'In2Brands BV',
  'BNEPODBSP': 'In2Brands BV',
  'BNEPOFDBCS': 'In2Brands BV',
  'BNEPOMQCBTBS': 'In2Brands BV',
  'BNEPOMDCBTW': 'In2Brands BV',
  'BNEPOMDCBTBS': 'In2Brands BV',
  'BNEPOMSA': 'In2Brands BV',
  'BNEPOMSCBTBS': 'In2Brands BV',
  'BNEPRF10': '"Dongguan Lingjie Electronics & Technology Co., Ltd / HK Forter Electronics Co., "',
  'BNEPRFWR': '"Dongguan Lingjie Electronics & Technology Co., Ltd / HK Forter Electronics Co., "',
  'BNEPRFWRDG': '"Dongguan Lingjie Electronics & Technology Co., Ltd / HK Forter Electronics Co., "',
  'BNEPRFP3MVML': '"Shenzhen Keyceo Tech Co.,Limited"',
  'BNEPRFP3MVMR': '"Shenzhen Keyceo Tech Co.,Limited"',
  'BNEPRFDG': '"Dongguan Lingjie Electronics & Technology Co., Ltd / HK Forter Electronics Co., "',
  'BNEPFB1330': '3M Nederland',
  'BNEPFB1400': '3M Nederland',
  'BNEPF1560B': '3M Nederland',
  'BNEPFB1560': '3M Nederland',
  'BNEPFB2200': '3M Nederland',
  'BNEPFB1250': '3M Nederland',
  'BNEPFAIPP66S78': '3M Nederland',
  'BNEPFAIP66S78': '3M Nederland',
  'BNEPFAIPXR': '3M Nederland',
  'BNEPFAIPXSX': '3M Nederland',
  'BNEPFG1250': '3M Nederland',
  'BNEPFG1330': '3M Nederland',
  'BNEPFG1400': '3M Nederland',
  'BNEPFG1560': '3M Nederland',
  'BNEPFSP34': '3M Nederland',
  'BNEHCPFPR5': '3M Nederland',
  'BNEPF215W': 'Adveo Nederland BV',
  'BNEPRM340': 'Entiris',
  'BNEFRP952': 'Score BV',
  'ZZZ_PRO_BNEPRO952ESD': 'Score BV',
  'BNEFRP959': 'Score BV',
  'BNEMAPBF1000': 'Drukland',
  'BNEMAPCBDE': 'MultiCopy',
  'BNEMAPCBEN': 'MultiCopy',
  'BNEMAPCBFR': 'MultiCopy',
  'BNEMAPCBNL': 'MultiCopy',
  'BNEMAPCE': 'MultiCopy',
  'ZZZ_CHAIRS_Profim Armlegger P59PU (set)': 'Flokk BV',
  'ZZZ_Chair_Profim_0GHEVF': 'Flokk BV',
  'BNEPLU250SLB3DH': 'Flokk BV',
  'BNEPLU250SLB3DS': 'Flokk BV',
  'ZZZ_Chairs_PFRC75': 'Flokk BV',
  'BNEUSFMBPNT1317': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSFMBP1315': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSFMBP1317NTB': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSFMBP1317': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSFMBP1515': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSFMBP1517': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEQB85': 'Monterey International Corp.',
  'BNEQB85B': 'Monterey International Corp.',
  'BNEQDM150': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC100CGRN': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC100CLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC100': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC100SP': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC400': 'Unfolding BV          FAILLIET',
  'BNEQDOC415': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC415S': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC500': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC500F': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEQDOC515CGRN': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC515CLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC515': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC515S': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC515SSP': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC515SP': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQDOC515A': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEQNOTE350': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR100': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR110CGRN': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR110CLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR110': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR130': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR140': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR50CGRN': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR50CLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR50': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR90CGRN': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR90CLGY': 'Reijnders Graveer & Lasertechniek BV',
  'BNEQR90': 'Reijnders Graveer & Lasertechniek BV',
  'ZZZ_Chairs_Revo1': 'Flokk BV',
  'ZZZ_Chairs_Revo2': 'Flokk BV',
  'ZZZ_RH LOGIC BLACK ELITE XL_0NPXTE': 'Flokk BV',
  'ZZZ_CHAIRS_RH_Logic220Elite_0HUA75': 'Flokk BV',
  'BNERHL220B8LH': 'Flokk BV',
  'BNERHL220B8LS': 'Flokk BV',
  'ZZZ_Chairs_RH LOGIC 220_SP201': 'Flokk BV',
  'ZZZ_CHAIR_05612D': 'Flokk BV',
  'BNERHL220XLB8LH': 'Flokk BV',
  'BNERHL220XLB8LS': 'Flokk BV',
  'ZZZ_RH Logic_0EZ7FK': 'Flokk BV',
  'ZZZ_Chairs_RH Logic wielen_125177-D': 'Flokk BV',
  'BNEROCKMWL': 'Microtouch Technology Inc.',
  'BNEROCKMWMS': 'Microtouch Technology Inc.',
  'BNERMBA': 'Copaco Nederland B.V.',
  'BNERMFB': 'Backshop BV',
  'BNERMF3W': 'Backshop BV',
  'CDRMPRO20310': 'Copaco Nederland B.V.',
  'CDRMPRO20210': 'Copaco Nederland B.V.',
  'CDRMPRO20110': 'Copaco Nederland B.V.',
  'CDRMPRO10310': 'Copaco Nederland B.V.',
  'CDRMPRO10210': 'Copaco Nederland B.V.',
  'CDRMPRO10110': 'Copaco Nederland B.V.',
  'BNERMB': 'Backshop BV',
  'BNERMPP': 'Backshop BV',
  'BNERMRAS': 'Backshop BV',
  'BNERMREDM': 'Backshop BV',
  'BNERMREDP': 'Backshop BV',
  'BNERMREDPW': 'Backshop BV',
  'BNERMRED': 'Backshop BV',
  'BNERMREDW': 'Backshop BV',
  'BNERMWB2': 'De ErgoShop',
  'BNESCB19': '"Amazon EU S.à r.l.,"',
  'BNES840DBE': 'We Fabricate B.V.',
  'BNES840DDE': 'We Fabricate B.V.',
  'BNES840DGESW': 'We Fabricate B.V.',
  'BNES840DES': 'We Fabricate B.V.',
  'BNES840DFR': 'We Fabricate B.V.',
  'BNES840DICE': 'We Fabricate B.V.',
  'BNES840DIT': 'We Fabricate B.V.',
  'BNES840DNOR': 'Monterey International Corp.',
  'BNES840DUK': 'We Fabricate B.V.',
  'BNES840DUS': 'We Fabricate B.V.',
  'BNES840DNHUK': 'Monterey International Corp.',
  'BNES840DNHUS': 'We Fabricate B.V.',
  'BNES840DNUM': 'We Fabricate B.V.',
  'BNES860BRDE': 'Monterey International Corp.',
  'BNES860BRDESW': 'Monterey International Corp.',
  'BNESR': 'Dutch Design Productions BV - Tristan Frencken',
  'BNESR5015': 'Dutch Design Productions BV - Tristan Frencken',
  'SVRL2017': 'Backshop BV',
  '"ZZZ_ARMS_Single Spacearm QC': 'GM Mount Bl",Adapt Deutschland GmbH',
  'BNESTH-PC': 'Ticken BV',
  'BNESTH-LT': 'Ticken BV',
  'BNESTH-US': 'Ticken BV',
  'CDSMPRO20310': 'Copaco Nederland B.V.',
  'CDSMPRO20210': 'Copaco Nederland B.V.',
  'CDSMPRO20110': 'Copaco Nederland B.V.',
  'CDSMPRO10310': 'Copaco Nederland B.V.',
  'CDSMPRO10210': 'Copaco Nederland B.V.',
  'CDSMPRO10110': 'Copaco Nederland B.V.',
  'BNESO12': 'Loctek Ningbo International Trading Co. Ltd',
  'BNESO11': 'Loctek Ningbo International Trading Co. Ltd',
  'BNESM865': 'Monterey International Corp.',
  'BNESOBFBSBSW': 'Flokk BV',
  'ZZZ_CHAIR_04W1BF+3D Top': 'Flokk BV',
  'BNESOFI7300BSBH': 'Flokk BV',
  'BNESOFI7300BSBS': 'Flokk BV',
  'BNESOFHM': 'Flokk BV',
  'BNESOFH': 'Flokk BV',
  'BNESOFM': 'Flokk BV',
  'BNESOFG200': 'Flokk BV',
  'BNESOFDS': 'Flokk BV',
  'BNESOFFBA': 'Flokk BV',
  'BNESOFFR': 'Flokk BV',
  'BNESOFHR': 'Flokk BV',
  'BNESOFARP': 'Flokk BV',
  'BNESOFARPB': 'Flokk BV',
  'BNESOFARA': 'Flokk BV',
  'BNESOFARPA': 'Flokk BV',
  'BNESOF3D': 'Flokk BV',
  'BNESOFSB': 'Flokk BV',
  'BNESOFLT': 'Flokk BV',
  'BNESPCZNKB': 'Adapt Deutschland GmbH',
  'BNESPDADCB': 'Adapt Deutschland GmbH',
  'BNESPDADC': 'Adapt Deutschland GmbH',
  'ZZZ_BNESPDADC': 'Adapt Deutschland GmbH',
  'BNESPLPOWA': 'Adapt Deutschland GmbH',
  'BNESPLPOWAB': 'Adapt Deutschland GmbH',
  'BNESPLEZC': 'Adapt Deutschland GmbH',
  'BNESPCZNK': 'Adapt Deutschland GmbH',
  'BNESPLACKB': 'Adapt Deutschland GmbH',
  'ZZZ_HB02-PLT': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_AR0011-950': 'Adapt Deutschland GmbH',
  'ZZZ_SAM118': 'Adapt Deutschland GmbH',
  'BNESPADCB': 'Adapt Deutschland GmbH',
  'BNESPADCMO': 'Adapt Deutschland GmbH',
  'BNESPBDBT': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_ SPBDCW': 'Adapt Deutschland GmbH',
  'ZZZ_BNESPBDCB': 'Adapt Deutschland GmbH',
  'BNESPBDGRM': 'Adapt Deutschland GmbH',
  'BNESPBD': 'Adapt Deutschland GmbH',
  'BNESPBTO': 'Adapt Deutschland GmbH',
  'BNESPBW': 'Adapt Deutschland GmbH',
  'BNESPWVA': 'Adapt Deutschland GmbH',
  'BNESPBTZ': 'Adapt Deutschland GmbH',
  'BNESPBTELNQCL': 'Adapt Deutschland GmbH',
  'BNESPBTS': 'Adapt Deutschland GmbH',
  'BNESPBTRO': 'Adapt Deutschland GmbH',
  'BNESPBTROS': 'Adapt Deutschland GmbH',
  'BNESPBTDHOS': 'Adapt Deutschland GmbH',
  'BNESPCHL': 'Adapt Deutschland GmbH',
  'BNESPWNQCZ': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_HB00CC-PLT': 'Adapt Deutschland GmbH',
  'BNESPL': 'Adapt Deutschland GmbH',
  'BNESPLP4': 'Adapt Deutschland GmbH',
  'BNESPZB': 'Adapt Deutschland GmbH',
  'ZZZ_BNESPBNQC': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_BNESPCLONHB': 'Adapt Deutschland GmbH',
  'BNESPCLOS': 'Adapt Deutschland GmbH',
  'BNESPCLOSB': 'Adapt Deutschland GmbH',
  'BNESPNQC': 'Adapt Deutschland GmbH',
  'BNESPCO': 'Adapt Deutschland GmbH',
  'BNESPCOB': 'Adapt Deutschland GmbH',
  'BNESPS': 'Adapt Deutschland GmbH',
  'BNESPZW': 'Adapt Deutschland GmbH',
  'BNESPDCLWNQCLLSZ': 'Adapt Deutschland GmbH',
  'ZZZ_Space Double aboveDesk Black': 'Adapt Deutschland GmbH',
  'ZZZ_Space Double aboveDesk Platinum  C': 'Adapt Deutschland GmbH',
  'BNESPDCWAB': 'Adapt Deutschland GmbH',
  'BNESPOBG': 'Adapt Deutschland GmbH',
  'BNESPDB': 'Adapt Deutschland GmbH',
  'ZZZ_ARM_SPDB': 'Adapt Deutschland GmbH',
  'BNESPDBT': 'Adapt Deutschland GmbH',
  'BNESPDBTB': 'Adapt Deutschland GmbH',
  'BNESPDBTELNQCL': 'Adapt Deutschland GmbH',
  'BNESPDBTNQC': 'Adapt Deutschland GmbH',
  'BNESPDBTW': 'Adapt Deutschland GmbH',
  'BNESPDWNQCZ': 'Adapt Deutschland GmbH',
  'BNESPDZ': 'Adapt Deutschland GmbH',
  'BNESPDZB': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_BNESPDBNQC': 'Adapt Deutschland GmbH',
  'BNESPDCLWLP': 'Adapt Deutschland GmbH',
  'ZZZ_BNESPDCLBNQCLLS': 'Adapt Deutschland GmbH',
  'BNESPDS2': 'Adapt Deutschland GmbH',
  'BNESPDGR': 'Adapt Deutschland GmbH',
  'BNESPDGRW': 'Adapt Deutschland GmbH',
  'BNESPDHO': 'Adapt Deutschland GmbH',
  'BNESPDLMC': 'Adapt Deutschland GmbH',
  'BNESPDLMCZB': 'Adapt Deutschland GmbH',
  'BNESPDL': 'Adapt Deutschland GmbH',
  'BNESPDLCLB': 'Adapt Deutschland GmbH',
  'BNESPDOTBT': 'Adapt Deutschland GmbH',
  'BNESPRSD': 'Adapt Deutschland GmbH',
  'BNESPDSL': 'Adapt Deutschland GmbH',
  'BNESPD': 'Adapt Deutschland GmbH',
  'BNESPDW': 'Adapt Deutschland GmbH',
  'BNESPEAECKB': 'Adapt Deutschland GmbH',
  'BNESPGRZ': 'Adapt Deutschland GmbH',
  'BNESPGRB': 'Adapt Deutschland GmbH',
  '"ZZZ_ARMS_Space-arm Grommet Black(7': '5-14)",Adapt Deutschland GmbH',
  'BNESPGRBNQC': 'Adapt Deutschland GmbH',
  'BNESPGRO': 'Adapt Deutschland GmbH',
  'BNESPLPO': 'Adapt Deutschland GmbH',
  'BNESPLCNH': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_SPSAM135': 'Adapt Deutschland GmbH',
  'BNESPLO': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_BNESPLCLBNQC': 'Adapt Deutschland GmbH',
  'BNESPLGRBNQC': 'Adapt Deutschland GmbH',
  'BNESPMCC': 'Adapt Deutschland GmbH',
  'BNESPNKGTB': 'Adapt Deutschland GmbH',
  'BNESPNTDC': 'Adapt Deutschland GmbH',
  'BNESPNTDGTB': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_SA01NK-CL BLK-950 No Top Knuckl': 'Adapt Deutschland GmbH',
  'BNESPOB': 'Adapt Deutschland GmbH',
  'BNESPOBZ': 'Adapt Deutschland GmbH',
  'BNESPOBC': 'Adapt Deutschland GmbH',
  'BNESPOBCB': 'Adapt Deutschland GmbH',
  'BNESPOBCW': 'Adapt Deutschland GmbH',
  'BNESPQCAVMP': 'Adapt Deutschland GmbH',
  'BNESPQBT': 'Adapt Deutschland GmbH',
  'BNESPB': 'Adapt Deutschland GmbH',
  'BNESPBTB': 'Adapt Deutschland GmbH',
  'BNESPBT': 'Adapt Deutschland GmbH',
  'BNESPBTW': 'Adapt Deutschland GmbH',
  'BNESPGR': 'Adapt Deutschland GmbH',
  'BNESPGRW': 'Adapt Deutschland GmbH',
  'BNESPZ': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_HB01CL-SD0011QC-BLK': 'Adapt Deutschland GmbH',
  'BNESPSHB': 'Adapt Deutschland GmbH',
  'BNESPO': 'Adapt Deutschland GmbH',
  'BNESPRSS': 'Adapt Deutschland GmbH',
  'BNESP': 'Adapt Deutschland GmbH',
  'BNESPCW': 'Adapt Deutschland GmbH',
  'BNESPSLPCLB': 'Adapt Deutschland GmbH',
  'BNESPSCB': 'Adapt Deutschland GmbH',
  'BNESPSPLPB': 'Adapt Deutschland GmbH',
  'BNESPTH': 'Adapt Deutschland GmbH',
  'BNESPSM118': 'Adapt Deutschland GmbH',
  'BNESPW': 'Adapt Deutschland GmbH',
  'ZZZ_ARMS_VM-WM-PLT': 'Adapt Deutschland GmbH',
  'OFF_SEV': 'Reijnders Graveer & Lasertechniek BV',
  'ZZZ_ARMS_BNEFG820005-S': 'Fellowes Holdings B.V.',
  'BNESRACCD': 'Dutch Design Productions BV - Tristan Frencken',
  'BNESKBFR': 'Ingram Micro BV',
  'BNESMHA01': 'Sun-Flex AB',
  'BNESMT85': 'Sun-Flex AB',
  'ZZZ_Swopper_101': 'aeris GmbH',
  'BNETRAPO': 'Dutch Design Productions BV - Tristan Frencken',
  'BNETR': 'Dutch Design Productions BV - Tristan Frencken',
  'PRO_CHAIR': 'Flokk BV',
  'PRO_ARMS': 'In2Brands BV',
  'PROJECT': 'Reijnders Graveer & Lasertechniek BV',
  'BNEEMP': 'Spire Hub B.V.',
  'BNEEMPED': 'Success Compu China Ltd.',
  'BNEEMPNL': 'Success Compu China Ltd.',
  'BNETNCHBT': 'Orosound',
  'BNETNCHUSB': 'Orosound',
  'BNETPNCOH': 'Orosound',
  'BNETPNCOHBM': 'Orosound',
  'BNETPNCOHCEP': 'Orosound',
  'BNETPNCOHJC': 'Orosound',
  'BNETPNCOHRJ9C': 'Orosound',
  'BNETPNCOHSEP': 'Orosound',
  'BNETGZB65': 'Health2Work',
  'ZZZ_Togu ABS Zit-fit bal 65 cm Blauw': 'Health2Work',
  'BNEZFB75': 'Health2Work',
  'ZZZ_Togu ABS Zit-fit bal  75 cm Blauw': 'Health2Work',
  'BNETB160': 'De Vos Ergonomics BV',
  'BNETWRC': 'Success Compu China Ltd.',
  'BNETWRS': 'Success Compu China Ltd.',
  'BNEU940BE': '"Digimore Electronics Co., Ltd"',
  'BNEU940DE': '"Digimore Electronics Co., Ltd"',
  'BNEU940FR': '"Digimore Electronics Co., Ltd"',
  'BNEU940SW': '"Digimore Electronics Co., Ltd"',
  'BNEU940UK': '"Digimore Electronics Co., Ltd"',
  'BNEU940US': '"Digimore Electronics Co., Ltd"',
  'BNEU950BE': '"Digimore Electronics Co., Ltd"',
  'BNEU950DE': '"Digimore Electronics Co., Ltd"',
  'BNEU950FR': '"Digimore Electronics Co., Ltd"',
  'BNEU950SW': '"Digimore Electronics Co., Ltd"',
  'BNEU950UK': '"Digimore Electronics Co., Ltd"',
  'BNEU950US': '"Digimore Electronics Co., Ltd"',
  'BNEU950WBE': '"Digimore Electronics Co., Ltd"',
  'BNEU950WDE': '"Digimore Electronics Co., Ltd"',
  'BNEU950WFR': '"Digimore Electronics Co., Ltd"',
  'BNEU950WCH': '"Digimore Electronics Co., Ltd"',
  'BNEU950WUK': '"Digimore Electronics Co., Ltd"',
  'BNEU950WUS': '"Digimore Electronics Co., Ltd"',
  'BNEU950WSW': '"Digimore Electronics Co., Ltd"',
  'BNEU950V2BE': '"Digimore Electronics Co., Ltd"',
  'BNEU950V2DE': '"Digimore Electronics Co., Ltd"',
  'BNEU950V2FR': '"Digimore Electronics Co., Ltd"',
  'BNEU950V2UK': '"Digimore Electronics Co., Ltd"',
  'BNEU950V2US': '"Digimore Electronics Co., Ltd"',
  'BNEU950WV2BE': '"Digimore Electronics Co., Ltd"',
  'BNEU950WV2DE': '"Digimore Electronics Co., Ltd"',
  'BNEU950WV2FR': '"Digimore Electronics Co., Ltd"',
  'BNEU950WV2SW': '"Digimore Electronics Co., Ltd"',
  'BNEU950WV2CH': '"Digimore Electronics Co., Ltd"',
  'BNEU950WV2UK': '"Digimore Electronics Co., Ltd"',
  'BNEU950WV2US': '"Digimore Electronics Co., Ltd"',
  'BNEU955NUM': '"Digimore Electronics Co., Ltd"',
  'BNEU955V2': '"Digimore Electronics Co., Ltd"',
  'BNEU960SCBE': '"Digimore Electronics Co., Ltd"',
  'BNEU960SCCH': '"Digimore Electronics Co., Ltd"',
  'BNEU960SCDE': '"Digimore Electronics Co., Ltd"',
  'BNEU960SCFR': '"Digimore Electronics Co., Ltd"',
  'BNEU960SCSW': '"Digimore Electronics Co., Ltd"',
  'BNEU960SCUK': '"Digimore Electronics Co., Ltd"',
  'BNEU960SCUS': '"Digimore Electronics Co., Ltd"',
  'BNEU960V2BE': '"Digimore Electronics Co., Ltd"',
  'BNEU960V2CH': '"Digimore Electronics Co., Ltd"',
  'BNEU960V2DE': '"Digimore Electronics Co., Ltd"',
  'BNEU960V2FR': '"Digimore Electronics Co., Ltd"',
  'BNEU960V2SW': '"Digimore Electronics Co., Ltd"',
  'BNEU960V2UK': '"Digimore Electronics Co., Ltd"',
  'BNEU960V2US': '"Digimore Electronics Co., Ltd"',
  'BNEUSDLE6230': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDLE7240': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLEX230': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLEX240': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSMCPRO1317': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSMCPRO1319': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDL7389': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLEYOGA': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSTZ930': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSMSLP3135': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDL54005401': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDL5410': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSRDL5420': 'Reijnders Graveer & Lasertechniek BV',
  'BNEUSDL54805490': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDLE6430': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDLE6440': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDLE7440': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDLE7450': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP840G3': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP840D': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP840': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP8470P': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHPMT42': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHPB440G5': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET420': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET430D': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET430S': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET440D': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET440S': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET440SPWC': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET450': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET480': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET495': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLEX1CN': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSRLX1YG6PWC': 'Reijnders Graveer & Lasertechniek BV',
  'BNEUSPWCLEYOGA': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSTTZ40A': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDLE6410': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSRDL5520': 'Reijnders Graveer & Lasertechniek BV',
  'BNEUSMCPRO1515': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSMCPRO1519': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDL5580': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDL55805590': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDXPS15': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP8570P': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP850': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLES540': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET530': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSLET540P': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSTTZ50A': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP450': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSHP650': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSMACPRO15': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSD55205420': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSDLE6430U': 'Dutch Design Productions BV - Tristan Frencken',
  'BNEUSRLX1YG6': 'Reijnders Graveer & Lasertechniek BV',
  'BNEUSPWCTPX1G10': 'Reijnders Graveer & Lasertechniek BV',
  'BNEUSUDG': 'Reijnders Graveer & Lasertechniek BV',
  'BNEUSUPM': 'Reijnders Graveer & Lasertechniek BV',
  'BNEUASA': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNEUASEPAS': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNEUASEPRAS': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNEUASS': 'Matting AB',
  'BNEUMCL': 'Health2Work',
  'BNEUMCLW': 'Health2Work',
  'BNEUMCR': 'Backshop BV',
  'BNEUMCRW': 'Health2Work',
  'BNEUFLT': 'Forming Function Stockholm AB  (Kondator AB)',
  'BNECPUQC': 'Forming Function Stockholm AB  (Kondator AB)',
  'ZZZ_Universele wielen zwart 65 mm_Sofi': 'Flokk BV',
  'BNEUSBV': 'Monterey International Corp.',
  'BNECHUB3A4C': 'Shenzhen Fangeweida Technology',
  'BNEC2AA': '"Shenzhen Loyal Electronics Co., Ltd"',
  'ZZZ_VirtuFit Stoelfiets': 'Fitwinkel / Sporttrader B.V.',
  'BNEFWEVRLB': 'HPC Drukkerij B.V.',
  'BNEFWEVL4LB': 'HPC Drukkerij B.V.',
  'BNEFWEVR4LB': 'HPC Drukkerij B.V.',
  'BNEFWEVR4WBLB': 'HPC Drukkerij B.V.',
  'BNEFWEVR4BBLB': 'HPC Drukkerij B.V.',
  'BNEFWEVR4WLB': 'HPC Drukkerij B.V.',
  'BNEFWEVR4SLB': 'HPC Drukkerij B.V.',
  'BNEFWEVR4SWLB': 'HPC Drukkerij B.V.',
  'BNEFWEVRCCLB': 'HPC Drukkerij B.V.',
  'BNEFWEVRDLLB': 'HPC Drukkerij B.V.',
  'BNEFWEVRDLWLB': 'HPC Drukkerij B.V.',
  'BNEFWEVRDLB': 'HPC Drukkerij B.V.',
  'BNEFWEVRDWLB': 'HPC Drukkerij B.V.',
  'BNEFWEVRDSLB': 'HPC Drukkerij B.V.',
  'BNEFWEVRDSWLB': 'HPC Drukkerij B.V.',
  'BNEFWEVSRLB': 'HPC Drukkerij B.V.',
  'BNEWIAPTM': 'Five 4 U BV',
  'BNEWIAPTS': 'Five 4 U BV',
  'BNEWIDP': 'Five 4 U BV',
  'BNEWIPTS': 'Five 4 U BV',
  'BNEIP': 'Five 4 U BV',
  'BNEWIPM': 'Five 4 U BV',
  'BNEWIPS': 'ALSO Nederland B.V.',
  'BNEWWAK': 'Five 4 U BV',
  'BNEWK': 'Health2Work',
  'BNEMAWMBDE': 'MultiCopy',
  'BNEMAWMBEN': 'MultiCopy',
  'BNEMAWMBFR': 'MultiCopy',
  'BNEMAWMBNL': 'MultiCopy',
  'BNEWMDC': 'LINAK Actuator-Systems BV',
  'BNEWMDCU': 'LINAK Actuator-Systems BV',
  'BNELINWMDT': 'LINAK Actuator-Systems BV',
  'BNEWMDFBB1': 'LINAK Actuator-Systems BV',
  'BNEWMDFGB1': 'LINAK Actuator-Systems BV',
  'BNEWMDFB': 'LINAK Actuator-Systems BV',
  'BNEWMDFBC4': 'LINAK Actuator-Systems BV',
  'BNEWMDFGC4': 'LINAK Actuator-Systems BV',
  'BNEWMDFBC2': 'LINAK Actuator-Systems BV',
  'BNEWMDFGC2': 'LINAK Actuator-Systems BV',
  'BNEWMDFBT3': 'LINAK Actuator-Systems BV',
  'BNEWMDFGT3': 'LINAK Actuator-Systems BV',
  'BNEWMDFG': 'LINAK Actuator-Systems BV',
  'BNEWMDHFW': 'In2Brands BV',
  'BNEWMDHWTW120': 'In2Brands BV',
  'BNEWMDTA180': 'J. Kisch & Zonen B.V.',
  'BNEWMDTB160': 'J. Kisch & Zonen B.V.',
  'BNEWMDTO120': 'J. Kisch & Zonen B.V.',
  'BNEWMDTO160': 'J. Kisch & Zonen B.V.',
  'BNEWMDTO180': 'J. Kisch & Zonen B.V.',
  'BNEWMDTW120': 'Leeuwerik Plaat B.V.',
  'BNEWMDTW160': 'Leeuwerik Plaat B.V.',
  'BNEWMDUTPC': 'LINAK Actuator-Systems BV',
  'BNEWMDUTPS': 'LINAK Actuator-Systems BV',
  'BNEWMDPCTG': 'LINAK Actuator-Systems BV',
  'BNEWJVML': 'Backshop BV',
  'BNEWJVM': 'Backshop BV',
  '601215': 'Copaco Nederland B.V.',
  '601214': 'Copaco Nederland B.V.',
  'CDWRPRO00210': 'Copaco Nederland B.V.',
  '601212': 'Copaco Nederland B.V.',
  '601211': 'Copaco Nederland B.V.',
  'CDWRPRO00110': 'Copaco Nederland B.V.',
  '601217': 'Copaco Nederland B.V.',
  'CDWRRMPRO00310': 'Copaco Nederland B.V.',
  '601219': 'Copaco Nederland B.V.',
  'CDWRSMPRO00310': 'Copaco Nederland B.V.'
};

/**
 * Get supplier for a product code
 */
export function getSupplier(productCode: string | null): string | null {
  if (!productCode) return null;
  return SUPPLIER_MAPPINGS[productCode] || null;
}
